baseURL = "https://abdus.net"
languageCode = "en-us"
title = "Abdus S. Azad"

theme = "hugo-theme-fiber"              # theme name
disableKinds = []           # disable stuffs
enableGitInfo = true        # valuable git information
enableEmoji = true          # enables emoji support in content files

[params]
  title = "abdus.net"
  mainSections = ["posts"]

[menu]

  [[menu.main]]
    identifier = "me"
    name = "Me"
    url = "/me/"
    weight = 10


  [[menu.main]]
    identifier = "keys"
    name = "keys"
    url = "/keys/"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories"
    weight = 10

  [[menu.main]]
    identifier = "notes"
    name = "notes"
    url = "/notes/"
    weight = 10

[markup]
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 1

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
tabWidth = 2


[permalinks]
pages = "/:filename"
posts = "/:year/:title/"
notes = "/notes/:filename"
