baseURL = "https://abdus.xyz"
languageCode = "en-us"
title = "Abdus S. Azad"

theme = "reek"


[markup]
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 1

[markup.highlight]
codeFences = false
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
#style = "friendly"
tabWidth = 4
